---
- name: Install shfmt on Ubuntu
  ansible.builtin.apt:
    name: shfmt
    state: present
  when: ansible_os_family == "Debian"
  become: yes

- name: Install shfmt on macOS
  community.general.homebrew:
    name: shfmt
    state: present
  when: ansible_os_family == "Darwin"