---
- name: Install fzf on Ubuntu
  ansible.builtin.apt:
    name: fzf
    state: present
  when: ansible_os_family == "Debian"
  become: yes

- name: Install fzf on macOS
  community.general.homebrew:
    name: fzf
    state: present
  when: ansible_os_family == "Darwin"