---
- name: Install prerequisites (Ubuntu)
  apt:
    name:
      - curl
      - gnupg
      - ca-certificates
      - apt-transport-https
      - python3-debian
    state: present
    update_cache: yes
  become: true
  when: ansible_facts.os_family == "Debian"

- name: Create keyrings directory (Ubuntu)
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when: ansible_facts.os_family == "Debian"

- name: Add Microsoft signing key (Ubuntu)
  become: true
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/microsoft.asc
    mode: "0644"
  when: ansible_facts.os_family == "Debian"

- name: Add Microsoft SQL Server repository (Ubuntu)
  become: true
  deb822_repository:
    name: microsoft-prod
    types: deb
    uris: https://packages.microsoft.com/ubuntu/{{ ansible_facts.distribution_version }}/prod
    suites: "{{ ansible_facts.distribution_release }}"
    components: main
    architectures: amd64
    signed_by: /etc/apt/keyrings/microsoft.asc
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install sqlcmd tools (Ubuntu)
  become: true
  environment:
    ACCEPT_EULA: 'Y'
  apt:
    name:
      - mssql-tools18
      - unixodbc-dev
    state: present
    update_cache: yes
  when: ansible_facts.os_family == "Debian"

- name: Add sqlcmd to PATH (Ubuntu)
  lineinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    line: 'export PATH="$PATH:/opt/mssql-tools/bin"'
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Tap Microsoft MSSQL repo (macOS)
  homebrew_tap:
    name: microsoft/mssql-release
    state: present
  when: ansible_facts.os_family == "Darwin"

- name: Install sqlcmd (macOS)
  homebrew:
    name: sqlcmd
    state: present
  when: ansible_facts.os_family == "Darwin" 
