- name: Update package manager (Ubuntu)
  become: true
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update package manager (macOS)
  homebrew:
    update_homebrew: true
  when: ansible_os_family == "Darwin"
