- name: Install Ubuntu restricted extras (Ubuntu only)
  package:
    name: ubuntu-restricted-extras
    state: present
  when: ansible_os_family == "Debian"

- name: Install core packages (Ubuntu)
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - curl
    - htop
    - vim
    - wget
    - zsh
    - ncdu
    - tree
    - build-essential
    - openssh-server
    - smbclient
    - xsel
    - zip
    - unzip
    - python3-pip
    - python3-venv
    - socat
    - ripgrep
    - fd-find
    - net-tools
    - jq
  when: ansible_os_family == "Debian"

- name: Install core packages (macOS)
  homebrew:
    name:
      - curl
      - htop
      - vim
      - wget
      - zsh
      - ncdu
      - tree
      - openssh
      - xsel
      - zip
      - unzip
      - python3
      - socat
      - ripgrep
      - fd
      - jq
    state: present
  when: ansible_os_family == "Darwin"

- name: Get the zsh path
  shell: which zsh
  register: bin_zsh

- name: Set zsh as default shell
  shell: chsh -s "{{ bin_zsh.stdout }}"
  when: isnt_ci
