- name: Install ubuntu-restricted-extras
  package:
    name: ubuntu-restricted-extras
    state: present

- name: Install core packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - htop
    - vim
    - wget
    - zsh
    - ncdu
    - tree
    - build-essential
    - openssh-server
    - smbclient
    - xsel
    - zip
    - unzip
    - python3-pip
    - python3-venv
    - socat
    - fzf
    - ripgrep
    - fd-find
    - net-tools

- name: Gets the zsh path
  shell: which zsh
  register: bin_zsh

- name: Set zsh as default shell
  become_method: sudo
  shell: chsh -s /bin/zsh
  when: isnt_ci

- name: Install antibody
  become: true
  shell: curl -sfL git.io/antibody | sh -s - -b /usr/local/bin
