- name: Install tmux
  package:
    name: tmux
    state: present

- name: Clone TPM repository
  become: false
  git:
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: ~/.tmux/plugins/tpm
