#!/usr/bin/env python3
"""Tests for the require-generated-release-notes PreToolUse hook.

Run: python3 claude/hooks/tests/test_require_generated_release_notes.py
Uses stdlib unittest only, no third-party dependencies, identical on macOS and Linux.
"""

import unittest

from _harness import invoke, load_hook, run_standalone

HOOK = "require-generated-release-notes.py"
hook = load_hook(HOOK)

BLOCK = 2
ALLOW = 0


def run_hook(command, tool="Bash"):
    """Invoke the hook with a Bash command payload and return its exit code.

    :param command: the shell command the model would run
    :param tool: tool name to report
    :return: hook exit code (2 blocks, 0 allows)
    """
    return invoke(hook, {"tool_name": tool, "tool_input": {"command": command}}).returncode


class TestBlocked(unittest.TestCase):
    """A release created without the autogenerated notes must be refused."""

    def test_plain_create(self):
        """A bare create with no notes flags is blocked."""
        self.assertEqual(run_hook("gh release create 1.2.4"), BLOCK)

    def test_create_with_only_custom_notes(self):
        """Curated --notes alone does not satisfy the requirement."""
        self.assertEqual(run_hook('gh release create 1.2.4 --notes "hotfix"'), BLOCK)

    def test_create_with_notes_file(self):
        """A --notes-file alone does not satisfy the requirement."""
        self.assertEqual(run_hook("gh release create 1.2.4 --notes-file notes.md"), BLOCK)

    def test_create_with_repo_flag_before_subcommand(self):
        """A global flag between gh and release is still matched."""
        self.assertEqual(run_hook("gh --repo Org/Repo release create 1.2.4 --title 1.2.4"), BLOCK)

    def test_create_inside_compound_command(self):
        """A create hidden in a compound command is still matched."""
        self.assertEqual(run_hook("git push origin 1.2.4 && gh release create 1.2.4"), BLOCK)


class TestAllowed(unittest.TestCase):
    """Anything that already generates notes, or is not a release creation, passes."""

    def test_echo_naming_a_release(self):
        """A progress line that names a release is not creating one."""
        self.assertEqual(run_hook('echo "next: gh release create v1"'), 0)

    def test_create_with_generate_notes(self):
        """--generate-notes passes."""
        self.assertEqual(run_hook("gh release create 1.2.4 --generate-notes"), ALLOW)

    def test_create_with_generated_and_custom_notes(self):
        """Curated notes alongside --generate-notes pass."""
        self.assertEqual(
            run_hook('gh release create 1.2.4 --generate-notes --notes "hotfix"'),
            ALLOW,
        )

    def test_release_view_is_untouched(self):
        """Read-only release view is not a creation."""
        self.assertEqual(run_hook("gh release view 1.2.4"), ALLOW)

    def test_release_list_is_untouched(self):
        """Read-only release list is not a creation."""
        self.assertEqual(run_hook("gh release list --limit 5"), ALLOW)

    def test_release_edit_is_untouched(self):
        """Editing an existing release is out of scope."""
        self.assertEqual(run_hook("gh release edit 1.2.4 --notes-file notes.md"), ALLOW)

    def test_release_upload_is_untouched(self):
        """Attaching an asset is out of scope."""
        self.assertEqual(run_hook("gh release upload 1.2.4 app.aab"), ALLOW)

    def test_prose_mentioning_release_create_is_untouched(self):
        """Prose mentioning releases does not trip the guard."""
        self.assertEqual(run_hook("echo 'remember to gh-release the build'"), ALLOW)

    def test_non_bash_tool_is_untouched(self):
        """A non-Bash tool call is ignored."""
        self.assertEqual(run_hook("gh release create 1.2.4", tool="Write"), ALLOW)


class TestMalformedInput(unittest.TestCase):
    """The hook must never block on input it cannot parse."""

    def test_invalid_json_allows(self):
        """Unparseable stdin allows rather than blocks."""
        self.assertEqual(run_standalone(HOOK, stdin="not json").returncode, ALLOW)

    def test_missing_command_allows(self):
        """A payload with no command allows rather than blocks."""
        payload = {"tool_name": "Bash", "tool_input": {}}
        self.assertEqual(invoke(hook, payload).returncode, ALLOW)


class TestHeredocBodiesAreData(unittest.TestCase):
    """A heredoc body describing a release is not creating one."""

    def test_script_body_mentioning_release_create(self):
        """Writing a script that mentions the command is allowed."""
        cmd = "cat > release.md <<'EOF'\nRun gh release create 1.0.0 by hand.\nEOF"
        self.assertEqual(run_hook(cmd), ALLOW)

    def test_command_after_heredoc_still_blocked(self):
        """A real release following a heredoc is still caught."""
        cmd = "cat > notes.md <<'EOF'\nhello\nEOF\ngh release create 1.0.0 --notes-file notes.md"
        self.assertEqual(run_hook(cmd), BLOCK)


if __name__ == "__main__":
    unittest.main(verbosity=2)
