---
- name: Install GnuPG on Ubuntu
  ansible.builtin.apt:
    name: gnupg
    state: present
  when: ansible_os_family == "Debian"
  become: yes

- name: Install GnuPG on macOS
  community.general.homebrew:
    name: gnupg
    state: present
  when: ansible_os_family == "Darwin"