---
neovim_js_debug_version: "1.117.0"
neovim_lua_ls_version: "3.18.2"
neovim_selene_version: "0.31.0"
neovim_taplo_version: "0.10.0"
neovim_zls_version: "0.16.0"
neovim_rust_analyzer_version: "2026-07-13"
