---
- name: Install pgformatter on Ubuntu
  ansible.builtin.apt:
    name: pgformatter
    state: present
  when: ansible_os_family == "Debian"
  become: yes

- name: Install pgformatter on macOS
  community.general.homebrew:
    name: pgformatter
    state: present
  when: ansible_os_family == "Darwin"