# Interpreted, interactive, object-oriented programming language
brew "python@3.14"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Plugin manager for zsh, inspired by antigen and antibody
brew "antidote"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Isolated development environments using Docker
brew "docker-compose"
# Create Docker hosts locally and on cloud providers
brew "docker-machine"
# Improved top (interactive process viewer)
brew "htop"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Run a Kubernetes cluster locally
brew "minikube"
# NCurses Disk Usage
brew "ncdu"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Object-relational database system
brew "postgresql@14", restart_service: :changed
# Opinionated Lua code formatter
brew "stylua"
# Terminal multiplexer
brew "tmux"
# Extraction utility for .zip compressed archives
brew "unzip"
# Internet file retriever
brew "wget"
# Command-line program for getting and setting the contents of the X selection
brew "xsel"
# Compression and file packaging/archive utility
brew "zip"
# UNIX shell (command interpreter)
brew "zsh"
# App to build and share containerised applications and microservices
cask "docker-desktop"
cask "font-meslo-lg-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
vscode "anthropic.claude-code"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-mssql.data-workspace-vscode"
vscode "ms-mssql.mssql"
vscode "ms-mssql.sql-bindings-vscode"
vscode "ms-mssql.sql-database-projects-vscode"
vscode "ms-vscode-remote.remote-containers"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "yzhang.markdown-all-in-one"
npm "@angular/cli"
npm "@angular/language-server"
npm "@angular/language-service"
npm "@ansible/ansible-language-server"
npm "bash-language-server"
npm "corepack"
npm "diagnostic-languageserver"
npm "diff-so-fancy"
npm "dockerfile-language-server-nodejs"
npm "emmet-ls"
npm "eslint_d"
npm "eslint"
npm "markdown"
npm "prettier"
npm "sql-formatter"
npm "tern"
npm "tree-sitter-cli"
npm "typescript-language-server"
npm "typescript"
npm "vim-language-server"
npm "vscode-langservers-extracted"
npm "yaml-language-server"
