---
- name: Install PostgreSQL (Ubuntu)
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: yes
  become: true
  when: ansible_facts.os_family == "Debian"

- name: Install PostgreSQL (macOS)
  community.general.homebrew:
    name: postgresql
    state: present
  when: ansible_facts.os_family == "Darwin"

- name: Start PostgreSQL service (Linux)
  become: true
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true
  when: ansible_facts.os_family == "Debian"

- name: Start PostgreSQL service (macOS)
  ansible.builtin.command: brew services start postgresql
  when: ansible_facts.os_family == "Darwin"

- name: Verify psql installation
  ansible.builtin.command: psql --version
  register: psql_version
  changed_when: false

- name: Show version
  ansible.builtin.debug:
    msg: 'PostgreSQL installed: {{ psql_version.stdout }}'
