---
- name: Install PostgreSQL (Ubuntu)
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: yes
  become: true
  when: ansible_facts.os_family == "Debian"

- name: Install PostgreSQL (macOS)
  homebrew:
    name: postgresql
    state: present
  when: ansible_facts.os_family == "Darwin"

- name: Start PostgreSQL service (Linux)
  become: true
  systemd:
    name: postgresql
    state: started
    enabled: true
  when: ansible_facts.os_family == "Debian"

- name: Start PostgreSQL service (macOS)
  command: brew services start postgresql
  when: ansible_facts.os_family == "Darwin"

- name: Verify psql installation
  command: psql --version
  register: psql_version
  changed_when: false

- name: Show version
  debug:
    msg: 'PostgreSQL installed: {{ psql_version.stdout }}'
