- hosts: localhost
  vars:
    should_be_root: "{{ true if ansible_pkg_mgr != 'brew' else false }}"
  roles:
    # essentials
    - { role: common, tags: common }
    - { role: git, tags: git }
    - { role: gnupg, tags: gnupg }
    - { role: ssh, tags: ssh }

    # languages
    - { role: mise, tags: mise }
    - { role: uv, tags: uv }
    - { role: java, tags: java }
    - { role: node, tags: node }
    - { role: python, tags: python }
    - { role: ruby, tags: ruby }
    - { role: dotnet, tags: dotnet }

    # tools
    - { role: docker, tags: docker }
    - { role: gh, tags: gh }
    - { role: delta, tags: delta }
    - { role: jq, tags: jq }
    - { role: shfmt, tags: shfmt }
    - { role: shellcheck, tags: shellcheck }
    - { role: fzf, tags: fzf }
    - { role: zoxide, tags: zoxide }
    - { role: eza, tags: eza }
    - { role: bat, tags: bat }
    - { role: fswatch, tags: fswatch }
    - { role: poppler, tags: poppler }
    - { role: neovim, tags: neovim }
    - { role: powershell, tags: powershell }

    # databases
    - { role: postgresql, tags: postgresql }
    - { role: pgformatter, tags: pgformatter }
    - { role: sqlcmd, tags: sqlcmd }

    # terminal
    - { role: ghostty, tags: ghostty }

    # mobile / react native
    - { role: watchman, tags: watchman }
    - { role: android, tags: android }
