- hosts: localhost
  vars:
    should_be_root: "{{ true if ansible_pkg_mgr != 'brew' else false }}"
  vars_files:
    - vars/java.yml
  roles:
    - role: geerlingguy.java
      when: ansible_os_family == "Debian"
  tasks:
    # essentials:
    - include_tasks: tasks/apt.yml
    - include_tasks: tasks/core.yml

    # tools
    - include_tasks: tasks/android.yml
