- hosts: localhost
  vars:
    should_be_root: "{{ true if ansible_pkg_mgr != 'brew' else false }}"
  roles:
    # essentials
    - role: common
    - role: git
    - role: gnupg
    - role: ssh

    # languages
    - role: python
    - role: node
    - role: java
    - role: ruby

    # tools
    - role: docker
    - role: gh
    - role: delta
    - role: jq
    - role: shfmt
    - role: fzf
    - role: zoxide
    - role: eza
    - role: bat
    - role: fswatch

    # databases
    - role: postgresql
    - role: pgformatter
    - role: sqlcmd

    # terminal
    - role: ghostty
  tasks:
    - include_tasks: tasks/android.yml
      when: ansible_facts.os_family == "Debian"
