- hosts: localhost
  vars:
    should_be_root: "{{ true if ansible_pkg_mgr != 'brew' else false }}"
  vars_files:
    - vars/java.yml
    - vars/powerline.yml
  roles:
    - role: geerlingguy.java
    - role: nass600.powerline
      become: '{{ should_be_root }}'
  tasks:
    # essentials:
    - include_tasks: tasks/apt.yml
    - include_tasks: tasks/core.yml

    # tools
    - include_tasks: tasks/android.yml
