- src: geerlingguy.java
- src: geerlingguy.nodejs
- src: geerlingguy.docker
- src: geerlingguy.git
- src: geerlingguy.kubernetes
- src: geerlingguy.pip
- src: mjanser.powerline
- src: rkm.dotnet_core
- src: nickpack.android_sdk
