#!/usr/bin/env python3
"""PreToolUse(Bash) guard: block `gh release create` without GitHub's autogenerated notes.

Enforces the user's standing preference that every GitHub release carries the
autogenerated "What's Changed" section at minimum. Curated notes are welcome on top —
`gh` prepends them when `--notes`/`--notes-file` is combined with `--generate-notes`:

    gh release create 1.2.4 --generate-notes --notes "Hotfix for ..."

Without `--generate-notes` the release loses the PR list, contributor list and full
changelog link, which is the part nobody can reconstruct by hand later.

Exit 2 + stderr blocks the tool call and feeds the reason back to the model.

Scope is deliberately narrow: only `gh release create`. Read-only subcommands (view,
list, download) and `gh release edit`/`upload` are untouched, since editing a release
to change a title or attach an asset has nothing to do with notes composition.

What is being INVOKED is read from the command with heredoc bodies stripped, so a script or
document that merely mentions creating a release is not mistaken for creating one.
"""

import re
import sys

from _hookutil import read_bash_payload, strip_heredocs

# Global flags may sit between `gh` and the subcommand, e.g. `gh --repo X release create`.
GH_FLAGS = r"(?:\s+-{1,2}[\w-]+(?:[= ]\S+)?)*"

RELEASE_CREATE = re.compile(
    rf"\bgh\b{GH_FLAGS}\s+release{GH_FLAGS}\s+create\b",
    re.IGNORECASE,
)


def creates_release(cmd):
    """Report whether a shell command invokes `gh release create`.

    Matching the subcommand pair rather than the bare word "release" keeps prose and
    unrelated commands (`gh release view`, `gh release list`) from tripping the guard.

    :param cmd: full shell command, possibly compound
    :return: True when the command creates a GitHub release
    """
    return bool(RELEASE_CREATE.search(cmd))


def has_generated_notes(cmd):
    """Report whether the command opts into GitHub's autogenerated release notes.

    :param cmd: full shell command
    :return: True when --generate-notes is present
    """
    return bool(re.search(r"(?<![\w-])--generate-notes(?![\w-])", cmd))


def main():
    """Block a `gh release create` that omits GitHub's autogenerated release notes."""
    data, cmd = read_bash_payload()
    if data is None:
        sys.exit(0)

    code = strip_heredocs(cmd)

    if not creates_release(code) or has_generated_notes(code):
        sys.exit(0)

    print(
        "BLOCKED by user policy: every GitHub release must include the autogenerated "
        "release notes.\nAdd --generate-notes. Curated notes still work alongside it — "
        "gh prepends --notes/--notes-file to the generated section:\n"
        '  gh release create <tag> --generate-notes --notes "..."\n'
        "If the release already exists, regenerate with:\n"
        "  gh api repos/{owner}/{repo}/releases/generate-notes -f tag_name=<tag>",
        file=sys.stderr,
    )
    sys.exit(2)


if __name__ == "__main__":
    main()
