---
- name: Install zoxide on Ubuntu
  ansible.builtin.apt:
    name: zoxide
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: yes

- name: Install zoxide on macOS
  community.general.homebrew:
    name: zoxide
    state: present
  when: ansible_os_family == "Darwin"

- name: Verify zoxide installation
  ansible.builtin.command: zoxide --version
  register: zoxide_version
  changed_when: false

- name: Show zoxide version
  ansible.builtin.debug:
    msg: "{{ zoxide_version.stdout_lines[0] }}"
