---
- name: Install jq on Ubuntu
  ansible.builtin.apt:
    name: jq
    state: present
  when: ansible_os_family == "Debian"
  become: yes

- name: Install jq on macOS
  community.general.homebrew:
    name: jq
    state: present
  when: ansible_os_family == "Darwin"