---
node_version: "22"

npm_global_packages:
  - eslint
  - prettier
  - typescript
  - markdownlint-cli2
  - "@angular/cli"
  - "@nestjs/cli"
  - tree-sitter-cli
  - typescript-language-server
  - vscode-langservers-extracted
  - dockerfile-language-server-nodejs
  - yaml-language-server
  - "@angular/language-server"
  - "@angular/language-service"
  - emmet-ls
  - bash-language-server
  - vim-language-server
  - sql-formatter
  - "@ansible/ansible-language-server"